theme: jekyll-theme-minimal
title: Nathanael T. Bowley
description: My 2020 Programming Portfolio ## Welcome to My Portfolio Main page! I'm a 3rd year BSc student studying Psychology and Computer Science and this is my portfolio. See below for my major representative projects I have created. Questions? Email me at:[nathanbowley98@live.com](mailto:nathanbowley98@live.com)
logo: https://i.imgur.com/60HeTZ8.png
