theme: jekyll-theme-minimal
title: Nathanael T. Bowley
description: I'm a 3rd year BSc student studying Psychology and Computer Science who is a TA for CSCI1110, CSCI1105 and recently taken NESC3505 where I have become proficient at Neural Data Science.
logo: https://i.imgur.com/60HeTZ8.png
