theme: jekyll-theme-minimal
title: Nathanael T. Bowley
description: I'm a 3rd year TA for CSCI1110, CSCI1105 taking a BSc Dbl. Maj. in Psychology and Computer Science who has experience with Neural Data Science.
logo: https://i.imgur.com/60HeTZ8.png
